from .coco import COCO
from .voc import VOC
from .bdd import BDD
from .KITTI import KITTI
from .ade20k import ADE20K
from .cityscapes import CityScapes
from .tusimple import TUSimple
from .culane import CUlane
from .lane import lane